Repository AVEN-SW/CEMENT-Frontend, pull requests merged in 2023-09, with the labels that each got.

#5 feat: People 페이지 퍼블리싱 #4
  src/assets/member.png
  src/assets/member10.png
  src/assets/member11.png
  src/assets/member12.png
  src/assets/member13.png
  src/assets/member14.png
  src/assets/member2.png
  src/assets/member3.png
  src/assets/member4.png
  src/assets/member5.png
  src/assets/member6.png
  src/assets/member7.png
  src/assets/member8.png
  src/assets/member9.png
  src/components/UI/Header.tsx
  src/main.tsx
  src/pages/MainPage.tsx
  src/pages/PeoplePage.tsx
Labels: publishing

#7 feat: Benefit 페이지 퍼블리싱
  src/components/UI/Header.tsx
  src/main.tsx
  src/pages/BenefitPage.tsx
Labels: publishing

#9 feat: Portfolio 페이지 퍼블리싱
  src/components/UI/Header.tsx
  src/main.tsx
  src/pages/PortfolioPage.tsx
Labels: publishing

#11 feat: Culture 페이지 퍼블리싱 수정
  src/assets/third-gallery.png
  src/assets/third-gallery2.png
  src/components/Culture/ThirdGallery.tsx
  src/pages/CulturePage.tsx
Labels: publishing

#13 feat: Main 페이지 퍼블리싱 수정
  index.html
  src/assets/instagram.png
  src/assets/instagram10.png
  src/assets/instagram11.png
  src/assets/instagram12.png
  src/assets/instagram13.png
  src/assets/instagram14.png
  src/assets/instagram15.png
  src/assets/instagram16.png
  src/assets/instagram2.png
  src/assets/instagram3.png
  src/assets/instagram4.png
  src/assets/instagram5.png
  src/assets/instagram6.png
  src/assets/instagram7.png
  src/assets/instagram8.png
  src/assets/instagram9.png
  src/assets/main-sample.png
  src/assets/qr-code.svg
  src/components/InfinityScroll/InfinityScrollText.tsx
  src/components/InfinityScroll/ScrollingText.tsx
  src/components/UI/Header.tsx
  src/pages/MainPage.tsx
Labels: publishing

#15 feat: Culture 페이지 Resizing
  src/components/Culture/FirstGallery.tsx
  src/components/Culture/SecondGallery.tsx
  src/components/Culture/ThirdGallery.tsx
  src/pages/CulturePage.tsx
Labels: publishing

#19 hotfix: vite 파일 수정
  vite.config.ts
Labels: duplicate

#21 fix: Assets 이미지 윤곽선 없는 버전으로 교체
  src/assets/first-gallery.png
  src/assets/first-gallery2.png
  src/assets/second-gallery.png
  src/assets/second-gallery2.png
  src/assets/third-gallery.png
  src/assets/third-gallery2.png
  src/components/Culture/FirstGallery.tsx
  src/components/Culture/SecondGallery.tsx
Labels: fix

#23 fix: Header 수정
  src/components/UI/Header.tsx
  src/pages/MainPage.tsx
Labels: fix

#25 fix: Header 간격 및 사이즈 조정
  src/components/UI/Header.tsx
Labels: fix

#27 fix: 텍스트 리워크
  public/assets/first-gallery.png
  public/assets/first-gallery2.png
  public/assets/fonts/LINESeedKR-Bd.woff2
  public/assets/fonts/LINESeedKR-Rg.woff2
  public/assets/fonts/LINESeedKR-Th.woff2
  public/assets/instagram.png
  public/assets/instagram10.png
  public/assets/instagram11.png
  public/assets/instagram12.png
  public/assets/instagram13.png
  public/assets/instagram14.png
  public/assets/instagram15.png
  public/assets/instagram16.png
  public/assets/instagram2.png
  public/assets/instagram3.png
  public/assets/instagram4.png
  public/assets/instagram5.png
  public/assets/instagram6.png
  public/assets/instagram7.png
  public/assets/instagram8.png
  public/assets/instagram9.png
  public/assets/logo.png
  public/assets/main-image.png
  public/assets/main-sample.png
  public/assets/member.png
  public/assets/member10.png
  public/assets/member11.png
  public/assets/member12.png
  public/assets/member13.png
  public/assets/member14.png
  public/assets/member2.png
  public/assets/member3.png
  public/assets/member4.png
  public/assets/member5.png
  public/assets/member6.png
  public/assets/member7.png
  public/assets/member8.png
  public/assets/member9.png
  public/assets/qr-code.svg
  public/assets/sample.png
  public/assets/second-gallery.png
  public/assets/second-gallery2.png
  public/assets/third-gallery.png
  public/assets/third-gallery2.png
  src/components/Culture/FirstGallery.tsx
  src/components/Culture/SecondGallery.tsx
  src/components/Culture/ThirdGallery.tsx
  src/components/UI/Header.tsx
  src/pages/CulturePage.tsx
  src/pages/MainPage.tsx
  src/pages/PeoplePage.tsx
  src/pages/PortfolioPage.tsx
  src/style/GlobalStyle.tsx
Labels: fix

#29 feat: Main 페이지 지도 추가
  .gitignore
  index.html
  src/components/Maps/Map.tsx
  src/main.tsx
  src/pages/MainPage.tsx
Labels: feature

#31 fix: 화면 해상도에 맞게 레이아웃 수정
  src/pages/MainPage.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: fix

#33 fix: Vite 환경변수 에러 수정
  package.json
  vite.config.ts
Labels: fix

#35 fix: 무한 스크롤링 텍스트 배경 색상 변경
  src/components/InfinityScroll/InfinityScrollText.tsx
Labels: fix
